language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

install:
  - apt-get update
  - apt-get -y install git g++ make cmake nano libgtest-dev
  - cd /usr/src/gtest && cmake CMakeLists.txt && make && make install

script:
  ############################################################################
  # Build main and tests
  ############################################################################
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON -DBUILD_WEBSOCKET=OFF -DBUILD_TRAFFIC_SIMULATION=ON -DBUILD_VEHICLE_MODEL=ON ..
  - make
  - make test
