language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

install:
  - bash ./install_gtest.sh

script:
  ############################################################################
  # Build main and tests
  ############################################################################
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON ..
  - make
  - make test
  - make install
