language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

before_install:
  - cd /tmp && git clone https://github.com/google/googletest && cd googletest && mkdir build && cd build
  - cd /tmp/googletest/build && cmake .. && make && sudo make install

script:
  ############################################################################
  # Build main and tests
  ############################################################################
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON -DBUILD_WEBSOCKET=OFF -DBUILD_TRAFFIC_SIMULATION=ON -DBUILD_VEHICLE_MODEL=ON ..
  - make
  - make test
