language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

script:
  ############################################################################
  # Build main and tests
  ############################################################################
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON -DBUILD_WEBSOCKET=OFF -DBUILD_TRAFFIC_SIMULATION=ON -DBUILD_VEHICLE_MODEL=ON ..
  - make
  - make test
